// Three visual themes. Each one provides:
//  - cssVars: applied at the root container as CSS custom properties
//  - hero:    style overrides for the dark hero stat card
//  - chip:    style for the active color filter chip
//  - inputBg: search field background
//  - sparkAccent: line spark color override
//  - solidBg / solidFg: primary button color
//  - bodyClass: optional class to put on root for theme-specific tweaks
//
// Reference: Uzum Market's brand color is a vivid violet (~ #7000FF).

const THEMES = {
  // 1) Uzum Market — official violet, friendly, brand-aligned
  uzum: {
    label: 'Uzum Market',
    sub: 'Бренд маркетплейса',
    swatch: ['#7000ff', '#9b51ff', '#f5f2ff'],
    cssVars: {
      '--bg': '#f5f3fb',
      '--surface': '#ffffff',
      '--surface-2': '#faf8ff',
      '--line': '#ece6f7',
      '--line-2': '#f3eefb',
      '--ink': '#13092e',
      '--ink-2': '#3a2d67',
      '--muted': '#6b5e94',
      '--faint': '#a89dc8',
      '--accent': '#7000ff',
      '--accent-soft': '#ede0ff',
      '--brand': '#7000ff',
      '--brand-soft': '#ede0ff',
      '--green': '#0d8a4a',
      '--green-soft': '#dbf3e3',
      '--amber': '#d97706',
      '--amber-soft': '#fdf2e3',
      '--red': '#d92d20',
      '--red-soft': '#fde4e2',
      '--shadow-sm': '0 1px 2px rgba(70, 36, 168, .06)',
      '--shadow-md': '0 1px 2px rgba(70, 36, 168, .08), 0 6px 22px rgba(70, 36, 168, .07)',
      '--radius': '12px',
      '--ring': '0 0 0 3px rgba(112,0,255,.18)',
    },
    hero: {
      background: 'var(--surface)',
      color: 'var(--ink)',
      borderColor: 'var(--line)',
      shadow: 'var(--shadow-sm)',
      grid: 'var(--line)',
      labels: 'var(--muted)',
      candleUp: '#16a34a',
      candleDown: '#dc2626',
      accent: '#7000ff',
    },
    solidBg: '#7000ff', solidFg: '#ffffff',
    inputBg: '#f1ebfd',
    rowHover: '#faf7ff',
    uzumTint: '#f1eaff',
    whTint:   '#e6f5fc',
    radius: 12,
  },

  // 2) Трейдер — dark trading-desk theme, fits the candlestick metaphor
  trader: {
    label: 'Трейдер',
    sub: 'Тёмная аналитическая',
    swatch: ['#0a0d14', '#a78bfa', '#26a69a'],
    cssVars: {
      '--bg': '#0a0d14',
      '--surface': '#131722',
      '--surface-2': '#161b27',
      '--line': '#222838',
      '--line-2': '#1b2030',
      '--ink': '#f0f3fa',
      '--ink-2': '#c9cdd9',
      '--muted': '#787b86',
      '--faint': '#4d5160',
      '--accent': '#a78bfa',
      '--accent-soft': 'rgba(167,139,250,.16)',
      '--brand': '#a78bfa',
      '--brand-soft': 'rgba(167,139,250,.16)',
      '--green': '#26a69a',
      '--green-soft': 'rgba(38,166,154,.18)',
      '--amber': '#ffb74d',
      '--amber-soft': 'rgba(255,183,77,.16)',
      '--red': '#ef5350',
      '--red-soft': 'rgba(239,83,80,.18)',
      '--shadow-sm': '0 1px 2px rgba(0,0,0,.4)',
      '--shadow-md': '0 1px 2px rgba(0,0,0,.4), 0 8px 28px rgba(0,0,0,.45)',
      '--radius': '8px',
      '--ring': '0 0 0 3px rgba(167,139,250,.25)',
    },
    hero: {
      background: 'var(--surface)',
      color: 'var(--ink)',
      borderColor: 'var(--line)',
      shadow: 'var(--shadow-sm)',
      grid: 'var(--line)',
      labels: 'var(--muted)',
      candleUp: '#26a69a',
      candleDown: '#ef5350',
      accent: '#a78bfa',
    },
    solidBg: '#a78bfa', solidFg: '#0a0d14',
    inputBg: '#161b27',
    rowHover: '#171c28',
    uzumTint: 'rgba(167,139,250,.08)',
    whTint:   'rgba(14,165,233,.10)',
    radius: 8,
    dark: true,
  },

  // 3) Премиум — light editorial, cream background, generous spacing, deep violet
  premium: {
    label: 'Премиум',
    sub: 'Эдиториал, премиальный',
    swatch: ['#1f1b14', '#5b21b6', '#faf8f3'],
    cssVars: {
      '--bg': '#f6f2ea',
      '--surface': '#ffffff',
      '--surface-2': '#fbf8f1',
      '--line': '#e6e0d2',
      '--line-2': '#ede8db',
      '--ink': '#1c1812',
      '--ink-2': '#403a2d',
      '--muted': '#80785f',
      '--faint': '#b3aa8e',
      '--accent': '#5b21b6',
      '--accent-soft': '#ebe0fa',
      '--brand': '#5b21b6',
      '--brand-soft': '#ebe0fa',
      '--green': '#15803d',
      '--green-soft': '#dcefd9',
      '--amber': '#b45309',
      '--amber-soft': '#f5e6c8',
      '--red': '#b91c1c',
      '--red-soft': '#f4dcd8',
      '--shadow-sm': '0 1px 2px rgba(56, 40, 12, .05)',
      '--shadow-md': '0 1px 2px rgba(56, 40, 12, .06), 0 8px 28px rgba(56, 40, 12, .06)',
      '--radius': '16px',
      '--ring': '0 0 0 3px rgba(91,33,182,.18)',
    },
    hero: {
      background: 'var(--surface)',
      color: 'var(--ink)',
      borderColor: 'var(--line)',
      shadow: 'var(--shadow-sm)',
      grid: 'var(--line)',
      labels: 'var(--muted)',
      candleUp: '#15803d',
      candleDown: '#b91c1c',
      accent: '#5b21b6',
    },
    solidBg: '#1c1812', solidFg: '#ffffff',
    inputBg: '#f3efe4',
    rowHover: '#fbf8f1',
    uzumTint: '#ece2fa',
    whTint:   '#dceef5',
    radius: 16,
    editorial: true,
  },
};

Object.assign(window, { THEMES });
